# Generated by Django 5.0 on 2023-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(20, '★☆☆☆☆'), (40, '★★☆☆☆'), (60, '★★★☆☆'), (80, '★★★★☆'), (100, '★★★★★')], default=None),
        ),
    ]
